### PR TITLE
Support for multiline strings

### PR DESCRIPTION
**Pull request by johankool**

### CODE REVIEW

**Comment by larslockefeer** [comment]
Hey @johankool, thank you for your contribution and apologies for not getting back to you sooner.

I have pushed an additional commit with a slightly different approach that leverages the substitution mechanism that we already have in place. Moreover, I only applied the substitution for Android since in the current version of localicious, newlines are already supported for iOS.

To elaborate a bit, let's say we have the following `Localicipe`:

```
SHARED:
  Module:
    Feature:
      MultilineStrings:
        COPY:
          en: |-
            This is a multiline string that may contain <a href="about:blank">links</a>
            You better watch out!

            It may also contain empty lines to break up text into paragraphs.
          nl: |-
            Dit is een string van meerdere regels die <a href="about:blank">links</a> kan bevatten.
            Let maar eens op!

            De tekst kan zelfs witregels bevatten!
```

It renders out on Android and iOS like so:

```
# Android
<string name="Module_Feature_MultilineStrings_COPY">This is a multiline string that may contain &lt;a href&#x3D;&quot;about:blank&quot;&gt;links&lt;/a&gt;
You better watch out!

It may also contain empty lines to break up text into paragraphs.</string>

# iOS
"Module.Feature.MultilineStrings.COPY" = "This is a multiline string that may contain &lt;a href&#x3D;&quot;about:blank&quot;&gt;links&lt;/a&gt;
You better watch out!

It may also contain empty lines to break up text into paragraphs.";
```

UI elements on iOS are capable of coping with these multiline strings and rendering them correctly. However, to make this work on Android, I think we need to change the output to:

```
<string name="Module_Feature_MultilineStrings_COPY">This is a multiline string that may contain &lt;a href&#x3D;&quot;about:blank&quot;&gt;links&lt;/a&gt;\nYou better watch out!\n\nIt may also contain empty lines to break up text into paragraphs.</string>
```

After the changes I suggest in my commit, only the first newline character will be replaced but that issue will be fixed when we merge #20.

**Comment by johankool** [comment]
@larslockefeer At least Xcode wasn't happy if newlines weren't encoded as `\n`. I also need the special characters like `&` to not be URL encoded. It seems like you are using some html-based way of showing the texts in your app?

**Comment by larslockefeer** [comment]
For some strings we indeed have some HTML processing before assigning the texts into the UILabels but for most strings we don't. I'll double-check the iOS newline case again tomorrow and commit and release a fix if necessary or update here with how I made it work.

The reason for most of the bugs that you encountered is that we are still on a legacy implementation of this tool internally and there are apparently some misalignments between the implementations that we did not test for. My apologies for that.

**Comment by larslockefeer** [comment]
Hey @johankool, I had another look at the iOS newline case. If I write the following:

```
let basicViewController = UIViewController()
let label = UILabel()
label.numberOfLines = 2
label.text = """
Kijk hier
Dit is een tekst die over 2 regels loopt.
"""
basicViewController.view.backgroundColor = .white
basicViewController.view.addSubview(label)
basicViewController.view.putSubviewAtCenter(label)
basicViewController.addChild(rootViewController)
```

iOS renders a label with the newline included:

image

You say that Xcode wasn't happy about this; what complaint did it give you exactly?

**Comment by johankool** [comment]
Screen Shot 2020-03-02 at 13 55 34

**Comment by larslockefeer** [comment]
Interesting, it works perfectly for me 🤔

Which version of Xcode are you using and in what type of file do you put your Localization strings, a `.strings` file?

**Comment by johankool** [comment]
I am on Xcode 11.3.1 and use a `.strings` file indeed. I don’t recall ever having seen it work with actual newlines instead of `\n`.

**Comment by larslockefeer** [comment]
I cannot find documentation anywhere that this is indeed not supported, so I'm guessing there is some difference in setup between your project and ours :-)

What do you see in the pane on the right-hand side when you open your `.strings` file? For us it looks as follows:

image

Maybe for you a different filetype is selected? If that is not it, can you try to reproduce your error message with an empty/minimal project and share it with me?

**Pull request merged**
